### ISSUE TITLE
Possible update?

### ISSUE THREAD

**Issue by MaxKablaam** [magogware/godot-audiostreampd#2]
Hi, I'm interested in running PD patches in my Godot project and your repo here looks like it's pretty close to what I want.

I messed around with your example, and I'm seeing that the audio is being buffered into an `audiostream` object, and possibly because of this, the pitch can't be adjusted without latency (must wait for the count to finish). For my purposes, I don't need the audio to be streamed into the game, and can just play it from the PD `dac~` like normal. What I do require is real-time control from GDscript of my parameters in the PD patch. So sliders in Godot can adjust sounds in PD.

Are you thinking of updating this add-on at all? Would you consider adding the choice to use the `audiostream` and a new node that is more a real-time control interface?

I have zero experience with C++ for GDnative, but I'm attempting to teach myself some right now in order to make these kinds of adjustments to your add-on. Perhaps we can collaborate on an update or you can impart some of your experience to help me get my version working?

Cheers, great work!

**Comment by magogware** [comment]
Hey mate!

Thanks for your interest! I've actually had good results adjusting patch parameters (pitch and any other float or even list values) with minimal latency by reducing the size of the `audiostream` buffer to just a few milliseconds. It doesn't impact performance too badly at all, either. 

If that doesn't prove fruitful to you, I can't help much. A real time audio node (or any new audio node or resource beyond the simple extension I've made to AudioStreamGenerator in this add-on) requires, at least in Godot 3.x, developing a custom engine module; not impossible, but the documentation of the engine audio code is pretty much nonexistent (the tutorial [here](https://docs.godotengine.org/en/3.5/development/cpp/custom_audiostreams.html) doesn't work, see my Reddit post about it [here](https://www.reddit.com/r/godot/comments/o2kazd/has_anyone_actually_gotten_a_custom_audiostream/)). I'm not brave enough to venture into that wilderness at the moment, nor do I want to invest the time with Godot 4 on the horizon (which I've heard rewrites the audio engine). 

All the best of luck! Let me know how things progress because I can probably help at least a bit. I'm sure rummaging around my Reddit posts will show you the dive I've taken into the world of dynamic audio and Godot, and I'm happy to share what I've learned and do what I can.

**Comment by MaxKablaam** [comment]
Thanks for your prompt answer! If you don't mind, I'd like you to elaborate on a few things for me...

What is the distinction and relationship between `interval` and `buffer length`?

![KxyCpPuRYP](https://user-images.githubusercontent.com/55173884/183122569-74a2cc80-3627-40df-a11e-c83195fbefc3.png)
If I set them both to 0.1, then the sound plays accurately, but pressing the freq up/down buttons has a considerable delay. If I set `interval` to 0.1, and `buffer length` to 0.05, then the sustained buzz of the saw osc is interupted by a repeating pause. If I set them both to 0.01, then I get something that sounds a lot more like the cpu having trouble, but it could also just be those same pauses at a much faster rate. What settings would you recommend for them to get good audio fidelity along with real-time patch control?

This second question is more about the Godot engine and how it works with `libpd`, not your specific add-on. In order for sound to play, does it actually have to go through an `audiostream`? Is `libpd` not able to play directly through the `dac~` as if you were running Puredata alongside Godot?
I ask this because if I'm going to try my own version of integrating `libpd` into Godot, I would probably forego using the Godot sound engine at all, and do all sound 100% in `libpd`. I would create a node in Godot that simply switched on or off the Puredata dsp, and provides access to patch parameters.

Thanks again for the great work and helpful response!

**Comment by magogware** [comment]
Alrighty, so...

`interval` refers to how frequently the buffer is refilled (i.e.: it's available frames are filled with samples). `buffer length` refers to how many seconds worth of samples the AudioStreamGenerator stores. Note that refilling the buffer _doesn't_ replace any frames that already have samples (from a previous update) with new audio data; it only fills available frames with that new audio data. We'll address this in a moment. In a performance context, then, a lower `interval` value means lower latency but more processing demand, and a higher `buffer length` means more latency and also a higher processing demand, albeit in bursts, to fill a greater amount of frames with sample data. You can offset that with a lower `interval`... I'm sure you can see the fine line you have to tread in balancing these two. I have no optimal setting, I'm afraid; it depends on your sample rate, latency requirements, processing power, and so on.

To properly respond to the patch updating after sending it a message, the code could be updated to do a `playback.clear_buffer()` after calling one of the message sending functions. This would solve the issue of having to set a very low interval and buffer length just to keep latency reasonable. 

Regarding how libpd works: no, it can't play audio. All it does is process audio and return samples in the form of ints, floats, or doubles into a buffer you provide. To play those samples, you can either pipe them into Godot (which is what this add-on does using an AudioStreamGenerator), or roll your own solution. You'd have to do that outside of Godot, because GDScript can't do audio without Godot's audio engine. You could absolutely find some C library and use it in the GDNative part of your planned add-on, and then the only interfacing with Godot you need to do is to receive messages to send to the patch, which you can just steal from this add-on's codebase to do. Note that this route does require dealing with things like mixing and spatialisation manually.

I can outline more of that if you don't already have plans on how your add-on will work, and I'm happy to collaborate and serve in a non-programming capacity, but I don't have the time to properly commit (no pun intended) to your project much more than that. 

Lemme know if you need anything else! Happy to keep chatting here or we can message privately, but I think it serves the public and future audio programmers stumbling across this to keep it out in the open.

**Comment by MaxKablaam** [comment]
Wow, thank you so much for your very detailed response. Totally answered any lingering questions I had. I'm going to mess around with it a bit this afternoon and hopefully I'll have some good news to report back to you.
