### ISSUE TITLE
Example: Attempt to call function 'new' in base 'NativeScript' on a null instance.

### ISSUE THREAD

**Issue by michaelmariaott** [magogware/godot-audiostreampd#3]
Hello,

if I try to run the example, the debugger tells me it's trying to call function 'new' in base 'NativeScript' on a null instance (AudioStreamPd.gd:13 - at function: setup => pdstream = PdStream.start()) and I get the following error messages:

```
E 0:00:00.343   open_dynamic_library: Can't open dynamic library: /Users/me/Documents/Godot/pd_test/addons/audiostreampd/lib/mac/libpdstream.dylib, error: dlopen(/Users/me/Documents/Godot/pd_test/addons/audiostreampd/lib/mac/libpdstream.dylib, 0x0002): tried: '/Users/me/Documents/Godot/pd_test/addons/audiostreampd/lib/mac/libpdstream.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h')).
  <C++-Fehler>  Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
  <C++-Quellcode>platform/osx/os_osx.mm:1916 @ open_dynamic_library()
```
```
E 0:00:00.343   get_symbol: No valid library handle, can't get symbol from GDNative object
  <C++-Quellcode>modules/gdnative/gdnative.cpp:510 @ get_symbol()
```
```
E 0:00:00.343   init_library: No nativescript_init in "res://addons/audiostreampd/lib/mac/libpdstream.dylib" found
  <C++-Quellcode>modules/gdnative/nativescript/nativescript.cpp:1510 @ init_library()
```

**Comment by magogware** [comment]
This is an issue with Godot libraries on a Mac. macOS only looks for library dependencies for an app in specific directories, not recursively. As a result, running in debug mode (i.e. from the play button in the Godot editor) won't work unless you make a directory in the root of the project called `libs` and copy the `.dylib` file into that folder. Be sure to change the Nativescript resource to point to that new `.dylib` destination. 

I don't believe this workaround is necessary for exported projects, because Godot puts all libraries where they need to be upon export.

Let me know if this fixes it!

**Comment by magogware** [comment]
Any updates on this @michaelmariaott?
